### ISSUE TITLE
"Include in report" button doesn't work in scenario analysis application

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/scenario-analysis#18] opened 2019-10-04 10:47 UTC
Title says it all. "Include in report" button doesn't work.

Ah, moment: the screenshots do get included, we just don't get a pop-up to edit the title & text or any indication that this has happened.

**Comment by p-a-s-c-a-l** [comment] 2019-10-07 07:57
Duplicate of https://github.com/clarity-h2020/scenario-analysis/issues/3

**Closed by p-a-s-c-a-l** 2019-10-07 07:57 UTC
Labels: duplicate
